name: sidokare_mobile_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  provider: ^6.0.5
  google_fonts: ^4.0.3
  motion_toast: ^2.6.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/img_login.jpg
    - assets/img_register.png
  uses-material-design: true
