name: sidokare_mobile_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  provider: ^6.0.5
  google_fonts: ^4.0.3
  motion_toast: ^2.6.5
  otp_text_field: ^1.1.3
  flutter_otp_text_field: ^1.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img_login.jpg
    - assets/img_register.png
    - assets/nganjuk.png
    - assets/intro1.png
    - assets/sukses.png
    - assets/imagelupasandi.png
    - assets/imageotp.png
    - assets/imageubahsandi.png

  fonts:
    - family: DMsans
      fonts:
        - asset: assets/fonts/DMSansRegular.ttf
        - asset: assets/fonts/DMSansItalic.ttf
          style: italic
        - asset: assets/fonts/DMSansBold.ttf
          weight: 700
        - asset: assets/fonts/DMSansBoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/DMSansMedium.ttf
        - asset: assets/fonts/DMSansMediumItalic.ttf
          style: italic
